"""Simulator endpoints — serve WealthLens-Sim scenario dashboard JSON.

Exposes the microsimulator's published dashboard contract
(``wealthlens_sim.outputs.to_dashboard_json``) over the API: a scenario list and,
per scenario, the full ``low``/``central``/``high`` revenue intervals plus their
``provenance``, ``caveats``, ``interval_method`` and ``provenance_complete`` flags.

The payloads are precomputed JSON files under ``data/simulator/`` (generated by
``automation/data-pipelines/generate_simulator_dashboards.py``), served
statically — the backend does NOT
import the simulator at runtime (it is a separate package). This mirrors the CSV
pipeline + static-serve pattern behind ``/api/data``. The contract is passed
through **unmodified**: a chart must receive ``caveats`` and ``interval_method``
exactly as the simulator emitted them.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path as FilePath
from typing import Any

from fastapi import APIRouter, HTTPException, Path, Response

from app.routers.schemas import (
    SimulatorScenarioInfo,
    SimulatorScenarioListResponse,
)

logger = logging.getLogger("wealthlens.simulator")

router = APIRouter()

SIMULATOR_DIR = FilePath(__file__).resolve().parents[3] / "data" / "simulator"

# Scenario results are deterministic (seeded synth population), so cache hard.
_CACHE = "public, max-age=86400"  # 24 hours

# Required top-level keys every served payload must carry — guards against a
# hand-edited or schema-drifted fixture being served as a valid contract.
# ``provenance`` is required because the scenario page renders its
# assumptions_consumed citations; a provenance-less payload is rejected here
# rather than crashing the client render.
_REQUIRED_KEYS = (
    "schema_version",
    "total_revenue_gbp_bn",
    "caveats",
    "interval_method",
    "provenance",
)

# Available scenarios. The ``name`` MUST equal the generator's scenario name (it
# flows into the fixture's ``scenario_name``; a drift-guard test enforces this).
# Source of truth for the ids/names is
# automation/data-pipelines/generate_simulator_dashboards.py. These are
# illustrative estimates over a SYNTHETIC v0.1 population, not official forecasts —
# the description says so. IHT scenarios are excluded until the synth IHT
# calibration lands: Tier A fixed the stock-vs-flow error (~£1009bn -> ~£21bn) but
# the headline is still ~3x the ~£7-8bn real figure (synth top-tail
# over-concentration); needs Tier B. See docs/IHT_CALIBRATION.md.
SIMULATOR_SCENARIOS: dict[str, dict[str, str]] = {
    "one-percent-wealth-tax": {
        "name": "1% annual wealth tax above £1m",
        "description": (
            "Illustrative estimate over a synthetic v0.1 population (not an official "
            "forecast): an annual 1% wealth tax on net wealth above £1,000,000."
        ),
    },
    "two-percent-wealth-tax": {
        "name": "2% annual wealth tax above £1m",
        "description": (
            "Illustrative estimate over a synthetic v0.1 population (not an official "
            "forecast): an annual 2% wealth tax on net wealth above £1,000,000."
        ),
    },
}


def _read_scenario(scenario_id: str) -> dict[str, Any]:
    """Read a scenario's dashboard JSON, raising 503 on any data problem.

    503 (not 500) when the precomputed file is missing, unreadable, not a JSON
    object, or missing required contract keys. The actionable detail (e.g. "run the
    generator") is *logged*; the global error handler returns a generic 503 body to
    clients, so no filesystem paths or exception strings leak.
    """
    path = SIMULATOR_DIR / f"{scenario_id}.json"
    if not path.exists():
        logger.warning(
            "Simulator scenario file not found: %s — run "
            "automation/data-pipelines/generate_simulator_dashboards.py",
            scenario_id,
        )
        raise HTTPException(status_code=503, detail="Scenario data not generated")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError, UnicodeDecodeError) as e:
        logger.error("Failed to read scenario '%s': %s", scenario_id, e)
        raise HTTPException(status_code=503, detail="Failed to read scenario data") from e
    if not isinstance(payload, dict) or not all(key in payload for key in _REQUIRED_KEYS):
        logger.error("Scenario '%s' payload is not a valid dashboard contract", scenario_id)
        raise HTTPException(status_code=503, detail="Scenario data is malformed")
    return payload


@router.get(
    "/",
    response_model=SimulatorScenarioListResponse,
    summary="List available simulator scenarios",
)
def list_scenarios(response: Response) -> dict[str, list[SimulatorScenarioInfo]]:
    """Return the available scenario ids with their names and descriptions."""
    response.headers["Cache-Control"] = _CACHE
    scenarios = [
        SimulatorScenarioInfo(id=scenario_id, name=meta["name"], description=meta["description"])
        for scenario_id, meta in SIMULATOR_SCENARIOS.items()
    ]
    return {"scenarios": scenarios}


@router.get(
    "/scenarios/{scenario_id}",
    summary="Get a scenario's dashboard JSON",
    response_description="The simulator dashboard contract (intervals + provenance + caveats).",
)
def get_scenario(
    response: Response,
    scenario_id: str = Path(
        ...,
        pattern=r"^[a-z0-9-]{1,50}$",
        description="Scenario identifier (lowercase, digits, hyphens only)",
    ),
) -> dict[str, Any]:
    """Return the full dashboard JSON for ``scenario_id``, passed through unmodified.

    404 for an unknown scenario; 503 if its data has not been generated yet.
    """
    if scenario_id not in SIMULATOR_SCENARIOS:
        raise HTTPException(status_code=404, detail=f"Unknown scenario: {scenario_id}")
    response.headers["Cache-Control"] = _CACHE
    return _read_scenario(scenario_id)
