"""Simulator endpoints — serve WealthLens-Sim scenario dashboard JSON.

Exposes the microsimulator's published dashboard contract
(``wealthlens_sim.outputs.to_dashboard_json``) over the API: a scenario list and,
per scenario, the full ``low``/``central``/``high`` revenue intervals plus their
``provenance``, ``caveats``, ``interval_method`` and ``provenance_complete`` flags.

The payloads are precomputed JSON files under ``data/simulator/`` (generated by
``automation/data-pipelines/generate_simulator_dashboards.py``), served
statically — the backend does NOT
import the simulator at runtime (it is a separate package). This mirrors the CSV
pipeline + static-serve pattern behind ``/api/data``. The contract is passed
through **unmodified**: a chart must receive ``caveats`` and ``interval_method``
exactly as the simulator emitted them.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path as FilePath
from typing import Any

from fastapi import APIRouter, HTTPException, Path, Response

from app.routers.schemas import (
    SimulatorScenarioInfo,
    SimulatorScenarioListResponse,
)

logger = logging.getLogger("wealthlens.simulator")

router = APIRouter()

SIMULATOR_DIR = FilePath(__file__).resolve().parents[3] / "data" / "simulator"

# Scenario results are deterministic (seeded synth population), so cache hard.
_CACHE = "public, max-age=86400"  # 24 hours

# Available scenarios. Keep this registry in sync with the ids produced by
# scripts/generate_simulator_data.py (the 404 check and the listing use it; the
# JSON files carry the actual numbers).
SIMULATOR_SCENARIOS: dict[str, dict[str, str]] = {
    "one-percent-wealth-tax": {
        "name": "1% annual wealth tax above £1m",
        "description": "An annual 1% wealth tax on net wealth above £1,000,000.",
    },
    "two-percent-wealth-tax": {
        "name": "2% annual wealth tax above £1m",
        "description": "An annual 2% wealth tax on net wealth above £1,000,000.",
    },
    "iht-current-baseline": {
        "name": "Inheritance tax — current-law baseline",
        "description": "Family D inheritance tax at current-law (2026-27) parameters.",
    },
    "wealth-tax-and-iht": {
        "name": "1% wealth tax above £1m plus the IHT baseline",
        "description": "A 1% annual wealth tax above £1m combined with the current IHT baseline.",
    },
}


def _read_scenario(scenario_id: str) -> dict[str, Any]:
    """Read a scenario's dashboard JSON, raising clear HTTP errors.

    503 when the precomputed file is missing or unreadable (so the caller gets a
    "run the generator first" hint rather than an opaque 500); the parsed payload
    is otherwise returned verbatim.
    """
    path = SIMULATOR_DIR / f"{scenario_id}.json"
    if not path.exists():
        logger.warning("Simulator scenario file not found: %s", scenario_id)
        raise HTTPException(
            status_code=503,
            detail=(
                f"Scenario data not generated: {scenario_id} — run "
                "automation/data-pipelines/generate_simulator_dashboards.py"
            ),
        )
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError, UnicodeDecodeError) as e:
        logger.error("Failed to read scenario '%s': %s", scenario_id, e)
        raise HTTPException(
            status_code=503,
            detail=f"Failed to read scenario '{scenario_id}': {e}",
        ) from e
    if not isinstance(payload, dict):
        raise HTTPException(
            status_code=503,
            detail=f"Scenario '{scenario_id}' payload is not a JSON object",
        )
    return payload


@router.get(
    "/",
    response_model=SimulatorScenarioListResponse,
    summary="List available simulator scenarios",
)
def list_scenarios(response: Response) -> dict[str, list[SimulatorScenarioInfo]]:
    """Return the available scenario ids with their names and descriptions."""
    response.headers["Cache-Control"] = _CACHE
    scenarios = [
        SimulatorScenarioInfo(id=scenario_id, name=meta["name"], description=meta["description"])
        for scenario_id, meta in SIMULATOR_SCENARIOS.items()
    ]
    return {"scenarios": scenarios}


@router.get(
    "/scenarios/{scenario_id}",
    summary="Get a scenario's dashboard JSON",
    response_description="The simulator dashboard contract (intervals + provenance + caveats).",
)
def get_scenario(
    response: Response,
    scenario_id: str = Path(
        ...,
        pattern=r"^[a-z0-9-]{1,50}$",
        description="Scenario identifier (lowercase, digits, hyphens only)",
    ),
) -> dict[str, Any]:
    """Return the full dashboard JSON for ``scenario_id``, passed through unmodified.

    404 for an unknown scenario; 503 if its data has not been generated yet.
    """
    if scenario_id not in SIMULATOR_SCENARIOS:
        raise HTTPException(status_code=404, detail=f"Unknown scenario: {scenario_id}")
    response.headers["Cache-Control"] = _CACHE
    return _read_scenario(scenario_id)
